//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CoreLibrary
{
    using System;
    using System.Collections.Generic;
    
    public partial class M_Application
    {
        public M_Application()
        {
            this.M_DocumentType = new HashSet<M_DocumentType>();
            this.T_User_Application_Map = new HashSet<T_User_Application_Map>();
        }
    
        public int ApplicationId { get; set; }
        public string ApplicationName { get; set; }
    
        public virtual ICollection<M_DocumentType> M_DocumentType { get; set; }
        public virtual ICollection<T_User_Application_Map> T_User_Application_Map { get; set; }
    }
}
