//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CoreLibrary
{
    using System;
    using System.Collections.Generic;
    
    public partial class T_Document
    {
        public T_Document()
        {
            this.T_Document_AuditLog = new HashSet<T_Document_AuditLog>();
        }
    
        public System.Guid DocumentId { get; set; }
        public System.Guid DocumentTypeId { get; set; }
        public System.Guid ParentLinkId { get; set; }
        public System.Guid ChildLinkId { get; set; }
        public string Tab { get; set; }
        public string Section { get; set; }
        public string Operation { get; set; }
        public string ViewModel { get; set; }
        public string XAMLFileName { get; set; }
        public string CommandName { get; set; }
        public string PropertyName { get; set; }
        public string PropertyDescription { get; set; }
        public string ServiceFileName { get; set; }
        public string ServiceMethodName { get; set; }
        public string ProcedureName { get; set; }
        public string Comments { get; set; }
        public string DocumentStatus { get; set; }
        public Nullable<System.Guid> CreatedById { get; set; }
        public Nullable<System.DateTimeOffset> CreatedByDate { get; set; }
        public Nullable<System.Guid> ModifiedById { get; set; }
        public Nullable<System.DateTimeOffset> ModifiedByDate { get; set; }
        public Nullable<int> SlNo { get; set; }
    
        public virtual M_ChildLink M_ChildLink { get; set; }
        public virtual M_DocumentType M_DocumentType { get; set; }
        public virtual M_ParentLink M_ParentLink { get; set; }
        public virtual M_User M_User { get; set; }
        public virtual M_User M_User1 { get; set; }
        public virtual ICollection<T_Document_AuditLog> T_Document_AuditLog { get; set; }
    }
}
