//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CoreLibrary
{
    using System;
    using System.Collections.Generic;
    
    public partial class T_Document_AuditLog
    {
        public System.Guid AuditLogId { get; set; }
        public System.Guid DocumentId { get; set; }
        public System.Guid UserId { get; set; }
        public System.DateTimeOffset AuditDate { get; set; }
        public string AuditDetails { get; set; }
        public string DocumentStatus { get; set; }
    
        public virtual M_User M_User { get; set; }
        public virtual T_Document T_Document { get; set; }
    }
}
