//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CoreLibrary
{
    using System;
    using System.Collections.Generic;
    
    public partial class T_User_Application_Map
    {
        public System.Guid UserId { get; set; }
        public int ApplicationId { get; set; }
        public string Status { get; set; }
    
        public virtual M_Application M_Application { get; set; }
        public virtual M_User M_User { get; set; }
    }
}
